---
title: "enrollment"
author: "Hamaad Mehal"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(googlesheets4)
library(ggplot2)

```

```{r}
sheets_deauth()

x <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA/edit#gid=0") %>%
  clean_names() %>%
  mutate(perc_red = red / (red + white))
```

```{r}
x

glimpse(x)

summary(x)
```

```{r}
x %>%
  arrange(desc(perc_red)) 

x %>%
  ggplot(aes(perc_red)) +
  geom_histogram(bins=20) +
  labs(title = "Percentage of Red Beads Drawn,",
       subtitle = "Should we be suspicious of those outliers?",
       caption = "Classroom data from 2020-03-03",
       x = "Percentage of Red Beads Out of 25 Drawn",
       y = "Count")
```

```{r}
library(infer)
urn <- tibble(
  bean_ID = 1:10000,
  color = c(rep("red", 2000), rep("white", 8000))
)

simulate_trial <- function(paddle_size) {
  urn %>% 
    rep_sample_n(size = paddle_size, reps = 51) %>% 
    group_by(replicate) %>% 
    summarize(red_sum = sum(color == "red")) %>% 
    mutate(perc_red = red_sum / paddle_size)
}




tibble(percs = map_dbl(1:1000, ~simulate_trial(25)$perc_red %>% mean())) %>% 
  ggplot(aes(percs)) + geom_histogram(bins = 20)

```
               
               
               color = c(rep("Red", 2000), rep("White",   8000)))